### PR TITLE
Run integration tests on multiple JVMs.

### PR DESCRIPTION
**Pull request by dmitry-timofeev**
- Add a script that sets up proper environment variables and launches
integration tests.
- Run tests with JDK 8 & JDK 9 on the CI service.

### CODE REVIEW

**Comment by dmitry-timofeev** [comment]
`cargo test …` doesn't rebuild the executable when `JAVA_HOME` changes :thinking: 

I wonder if it's possible to clean test binaries only? I can currently think only of a hack with `$ touch <some source file>`.

**Comment by alexander-irbis** [comment]
> I wonder if it's possible to clean test binaries only?

```
cargo clean -p jni
```

**Comment by dmitry-timofeev** [comment]
Updated the script and added `--verbose` to make sure it works as expected on Travis

**Comment by dmitry-timofeev** [comment]
Just a flaky build that couldn't download sth from Google: https://travis-ci.org/prevoty/jni-rs/jobs/326824201
@jechase , could you restart please?

**Pull request merged**
