### PR TITLE
Add 'Clone' and 'Copy' imlementations for the 'JNIEnv'

### PR DESCRIPTION
**Pull request by DarkEld3r**
`JNIEnv` is passed by value to the extern functions, so Clippy warns about "needless pass by value".
I suppose there is no harm in adding `Copy`?

### CODE REVIEW

**Comment by DarkEld3r** [comment]
Build is failing now because of this: https://github.com/sfackler/rust-jni-sys/pull/6. I'm going to send different pull request for that. :smile:

**Comment by DarkEld3r** [comment]
On second thought this can be unsafe, because with copy/clone there can be several mutable JNI-interfaces.

**Comment by sfackler** [comment]
Why is this unsafe?

**Comment by jechas01** [comment]
Right, I believe that adding Copy/Clone would break some guarantees that the JNIEnv wrapper tries to give you. It's not unsafe *per se*, but it throws the borrow/mutability checker out the window.

**Comment by DarkEld3r** [comment]
@jechas01 
Sorry for reopening, but I have another thought about this.

@sfackler 
At first I thought that if `Copy` and/or `Clone` is implemented, then someone can make a copy, pass it to another thread and call methods simultaneously. Then I remembered that `Copy` and `Send` are completely different things, so everything [should be OK](https://is.gd/aGBcbH).

So again, am I missing something or such implementations will not break anything? :sweat_smile:

**Comment by jechas01** [comment]
This still breaks mutability assumptions. Having Copy/Clone implemented means that you can get two mutable references to the JNI pointer simultaneously, which wouldn't be allowed with Rust's single-mutability principle. See https://play.rust-lang.org/?gist=8c5fa89bdbd14b13d1789cc44772f12d&version=stable&backtrace=1 as an example of what I'm talking about.

If this is *really* something that the library consumer needs, it can be accomplished via the `get_native_interface` method and the `From<*mut sys::JNIEnv>` implementations. This at least makes it obvious that something outside the norm is going on, rather than an implicit breaking of assumptions.

**Comment by DarkEld3r** [comment]
Now everything is clear, thank you.

**Pull request closed without merging**
